#!/usr/bin/env bash
# SOURCE
# to instantiate with this, add:
# tmp=`pwd`; # cd MPY_PATH/ && . mpy-init2 && cd $tmp
# to your bashrc

_mpy_resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

_mpy_abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"
  
  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(_mpy_resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

_mpy_source() {
  local out=`grep $'#[ \t]*SOURCE' $1`
  if [ "$out" == "" ]; then
    echo "0"
    return
  fi
  echo "1"
}

export MPY_PATH=`pwd`

case "$0" in
bash | zsh)
  source ../completions/mpy.$0
  ;;
-bash )
  source ../completions/mpy.bash
  ;;
esac

function mpy() {
    local original_path=$PATH
    local source_command=0
    export PATH="$MPY_PATH:$PATH"

    libexec_path=$MPY_PATH

    command="$1"
    case "$command" in
    "" | "-h" | "--help" )
      mpy-help
      ;;
    * )
      command_path="$(command -v "mpy-$command" || true)"
      if [ ! -x "$command_path" ]; then
        echo "mpy: no such command \`$command'"
      else
          source_command=$(_mpy_source $command_path)
          shift
          if [[ "$1" -eq "--complete" ]]; then
              $command_path "$@"
          elif [[ "$source_command" -eq 0 ]]; then
              $command_path "$@"
          else 
              . $command_path "$@"
          fi
      fi
      ;;
    esac
    export PATH=$original_path
}
